### ISSUE TITLE
Adding GitHub repo to metadata

### ISSUE THREAD

**Issue by oalders** [gbxyz/perl-net-rdap#1]
Thanks for your work on this module! I had to dig around a bit to find the repo, but if it's added to the metadata then MetaCPAN can link to here directly. Please see https://perlmaven.com/how-to-add-link-to-version-control-system-of-a-cpan-distributions for a quick overview.

**Comment by gbxyz** [comment]
Thanks for the suggestion, I'll do that for all my modules!
