### ISSUE TITLE
Thin Registry queries

### ISSUE THREAD

**Issue by markushopkins** [gbxyz/perl-net-rdap#4]
It appears that the only way to do the second step query (i.e., registrar query) on a Domain object is to call $rdap->fetch() on the link object with 'rel'=>'related' key/value.  Is that correct, or is there a more straight forward method for this that I'm missing?  Thanks.

**Comment by gbxyz** [comment]
Yes that's correct - the only way to find out which registrar sponsors a domain is to do a registry query and follow the link.

**Comment by markushopkins** [comment]
Hey thanks so much for responding.  Appreciate it.
